### ISSUE TITLE
Matches-any pseudo-class is not being calculated correctly

### ISSUE THREAD

**Issue by keeganstreet** [keeganstreet/specificity#1]
http://dev.w3.org/csswg/selectors4/#matches

This psuedo-class is already supported in many browsers http://caniuse.com/#search=matches

**Comment by papandreou** [comment]
I just ran into this as well while trying to calculate specificities for parse the Firefox default stylesheet:

```js
> require('specificity').calculate(':-moz-any(ul, ol, dir, menu, dl) ul');
[ { selector: ':-moz-any(ul',
    specificity: '0,0,1,0',
    specificityArray: [ 0, 0, 1, 0 ],
    parts: [ [Object] ] },
  { selector: ' ol',
    specificity: '0,0,0,1',
    specificityArray: [ 0, 0, 0, 1 ],
    parts: [ [Object] ] },
  { selector: ' dir',
    specificity: '0,0,0,1',
    specificityArray: [ 0, 0, 0, 1 ],
    parts: [ [Object] ] },
  { selector: ' menu',
    specificity: '0,0,0,1',
    specificityArray: [ 0, 0, 0, 1 ],
    parts: [ [Object] ] },
  { selector: ' dl) ul',
    specificity: '0,0,0,2',
    specificityArray: [ 0, 0, 0, 2 ],
    parts: [ [Object], [Object] ] } ]
```

**Comment by papandreou** [comment]
The [css-selector-tokenizer library](https://github.com/css-modules/css-selector-tokenizer) does support the construct, maybe it'd make sense to use that for the initial tokenization?

```js
require('css-selector-tokenizer').parse(':-moz-any(ul, ol, dir, menu, dl) ul, :-moz-any(ul, ol, dir, menu, dl) ol').nodes[0];
{ type: 'selector',
  nodes: 
   [ { type: 'pseudo-class',
       name: '-moz-any',
       content: 'ul, ol, dir, menu, dl' },
     { type: 'spacing', value: ' ' },
     { type: 'element', name: 'ul' } ] }
```

**Comment by keeganstreet** [comment]
Hey @papandreou, the problem is, the specificity of a selector with the matches-any pseudo-class varies depending on which option in the "any" list is matched.

> `:matches(em, #foo)` has a specificity of `(0,0,0,1)`, like a tag selector, when matched against `<em>`, and a specificity of `(0,1,0,0)`, like an ID selector, when matched against `<em id=foo>`.
https://drafts.csswg.org/selectors-4/#specificity-rules

If this calc is to support the matches-any pseudo-class, it will need to return potentially multiple specificity values for one selector.

**Comment by papandreou** [comment]
@keeganstreet, oh man, I see. Then it's even more complex than I thought. For the thing I'm working on, I ended up [manually exploding all the cases](https://github.com/assetgraph/assetgraph/commit/56c413f1c465f985f6c2226dfeeb910105c1de68). I guess you'll have to do something similar internally in order to support the different specificities. Yikes.

**Comment by jmiserez** [comment]
> 
> 
> Hey @papandreou, the problem is, the specificity of a selector with the matches-any pseudo-class varies depending on which option in the "any" list is matched.
> 
> > `:matches(em, #foo)` has a specificity of `(0,0,0,1)`, like a tag selector, when matched against `<em>`, and a specificity of `(0,1,0,0)`, like an ID selector, when matched against `<em id=foo>`.
> > https://drafts.csswg.org/selectors-4/#specificity-rules
> 
> If this calc is to support the matches-any pseudo-class, it will need to return potentially multiple specificity values for one selector.

I think that is incorrect, or maybe the specification has been updated since your comment. Now it says the following:

> Note: The specificity of the :is() pseudo-class is replaced by the specificity of its most specific argument. Thus, a selector written with :is() does not necessarily have equivalent specificity to the equivalent selector written without :is()
> For example, if we have :is(ul, ol, .list) > [hidden] and ul > [hidden], ol > [hidden], .list > [hidden] a [hidden] child of an ol matches the first selector with a specificity of (0,2,0) whereas it matches the second selector with a specificity of (0,1,1).
> 

That should be *much* easier to implement.
