### ISSUE TITLE
escaped characters not calculated correctly

### ISSUE THREAD

**Issue by geddski** [keeganstreet/specificity#10]
this is a valid class (using character escaping)

```css
#home .\[page\] {

}
```

specificity should be 0,1,1,0 (one id and one class). But it's being reported as 0,1,2,0 which makes me think it is incorrectly treating the brackets [] as an attribute selector even though they're escaped.

**Comment by keeganstreet** [comment]
This could be tricky to implement without introducing regression defects.

Some example selectors with unicode escape sequences below.
```css
.\3A \`\( { } /* matches elements with class=":`(" */
.\3A\`\( { } /* matches elements with class=":`(" */
.\31 a2b3c { } /* matches elements with class="1a2b3c" */
.\000031a2b3c { } /* matches elements with class="1a2b3c" */
.\000031 a2b3c { } /* matches elements with class="1a2b3c" */
#\#fake-id {} /* matches the element with id="#fake-id" */
#-a-b-c- {} /* matches the element with id="-a-b-c-" */
#© { } /* matches the element with id="©" */
```

Some helpful references below if we decide to go ahead and implement this:
https://mathiasbynens.be/notes/css-escapes
https://www.w3.org/TR/CSS21/syndata.html#characters

**Comment by keeganstreet** [comment]
Actually this wasn't hard at all. Its been fixed and is ready to merge in. Sorry its taken two years @geddski

**Comment by geddski** [comment]
Awesome thank you!

**Comment by keeganstreet** [comment]
Resolved by https://github.com/keeganstreet/specificity/pull/21
