### ISSUE TITLE
npm warning Specificity using legacy form of version dependency

### ISSUE THREAD

**Issue by AddictArts** [keeganstreet/specificity#14]
npm WARN engine specificity@0.1.4: wanted: {"node":"~0.8.x"} (current: {"node":"0.12.7","npm":"2.12.1"})

Any chance of changing to ^0.8.0, carrot syntax and maybe a newer node engine version. Many other node modules can no longer find versions supporting 0.8.x.

```javascript
"engines": {
		"node": "~0.8.x"
},
```

**Comment by keeganstreet** [comment]
This has been fixed by https://github.com/keeganstreet/specificity/pull/15
