### ISSUE TITLE
Error installing as a dependency

### ISSUE THREAD

**Issue by jeffjewiss** [keeganstreet/specificity#16]
Hi there, I'm running into an issue trying to install `cssstats`, which depends on `specificity`, with Node V4 and V5.

There's already a fix committed here: https://github.com/keeganstreet/specificity/commit/e73391e9388c565bf5dd4ff45fd8164951d629cc

However, it looks like this change hasn't been published to NPM. Any chance you could run `npm version patch && npm publish`?

Thanks for all the work you've put in to this module, cheers!

**Comment by keeganstreet** [comment]
Hey Jeff, thanks for debugging the issue and letting me know. I've published the patch to npm.

**Comment by jeffjewiss** [comment]
Thanks Keegan, that fixed the issue!
