### ISSUE TITLE
specificity calculator on commandline?

### ISSUE THREAD

**Issue by HansS** [keeganstreet/specificity#18]
is there a cli version of the calculator?

**Comment by keeganstreet** [comment]
Hi Hans, I haven't released a CLI version of the calc. But I have written one that sits inside a Sublime Text package. It uses Commander.js to expose this JS module on the command line. https://github.com/keeganstreet/sublime-specificity/blob/master/lib/specificity.js

**Comment by HansS** [comment]
Hi Keegan
thank's a lot for the link and your contribution!regardsHans

Date: Sun, 15 May 2016 02:39:49 -0700
