### ISSUE TITLE
Provide command-line script for computing specificity

### ISSUE THREAD

**Issue by prantlf** [keeganstreet/specificity#23]
When working off-line without access to the web site, it would be nice to be able to run a command-line tool, for example, which would be more lightweight, than running the entire web site locally.  For example:

```sh
$ specificity "ul#nav li.active a"
0,1,1,3
```

**Comment by keeganstreet** [comment]
Hi @prantlf, this sounds like a good idea. Thanks for the pull request. It looks great.

**Comment by keeganstreet** [comment]
I have published verion 0.3.0 to npm with this command line feature

**Comment by prantlf** [comment]
Thanks a lot for merging!  The script is very minimal and simplistic, but additional features like command-line parameter support or different formatting can be added easily depending on user feedback.  So far, I used it a lot and I didn't need more :-)
