### ISSUE TITLE
:not Pseudo-Class not recognized

### ISSUE THREAD

**Issue by TechTrain** [keeganstreet/specificity#27]
It seems that the :not() pseudo-class is not being picked up by the calculator. Has the calculator been updated to account for the Selectors L3 standard?

**Comment by keeganstreet** [comment]
Hi @TechTrain, sorry for the late reply. Yes the calculator does support the negation pseudo-class. You can see an example at http://specificity.keegan.st. For example paste in a selector like `li:not(.class)`.
