### ISSUE TITLE
Repeated IDs not counted.

### ISSUE THREAD

**Issue by KamikazeScotsman** [keeganstreet/specificity#29]
As stated in [the selector specificity section in the selectors level 3 documentation](https://www.w3.org/TR/css3-selectors/#specificity), "repeated occurrances of the same simple selector are allowed and do increase specificity". This includes classes and IDs, so the selector ".class.class.class" will have a higher specificity than ".class", "#id#id#id" will have a higher specificity than "#id", and "#id#id" will have a higher specificity than "#id.class". 

This is reflected in the result of the calculator for classes, but it is not for IDs. When I enter "#id#id.class.class" into the calculator, I get the result "0,1,2,0", but it should be "0,2,2,0".

**Comment by keeganstreet** [comment]
Good catch @KamikazeScotsman, that's definitely a bug in the calculator. I will look into it.
