### ISSUE TITLE
Provide function for basic bounds checking

### ISSUE THREAD

**Issue by jimbo** [keeganstreet/specificity#31]
One major use case for calculating specificity is ensuring it's not too high. Right now, this is done by using the `calculate` function and then comparing the result against a specificity array that represents some maximum specificity. However, the `compare` function doesn't always work for this use case: if you're interested in restricting one particular component of a selector, such as tag names, `compare` doesn't work at that granular level.

It would be nice to have a function that compared specificity at a more granular level—on a per-component basis. Obviously, that's an extension of the scope of this module, so I'd understand if you're not interested. I'm happy to write the function, though. What are your thoughts?

**Comment by keeganstreet** [comment]
Hi Jimbo,

Sorry for the late reply. I appreciate your thoughts and the code you've written. But I don't think it really fits into this module.

If you want to have a CSS code linting rule like "allow selectors to have 1 ID part and 3 classname parts", that's fine, but its not technically linting the _specificity_. A selector with 4 classname parts still has a lower specificity than a selector with 1 ID part and 3 classname parts.

This might sound like a technicality but I want to keep this module purely focused on specificity. Validating selectors based on the number of parts is an additional layer of subjective rules. Maybe you would like to release a separate npm package for selector part bounds checking and import specificity calculator in as a dependency?

Cheers,
Keegan

**Comment by jimbo** [comment]
@keeganstreet Thanks for the response. I understand your perspective; my proposal was a long shot as far as being in scope for this module, but I wanted to try since it seemed like a convenient place for the function to live.

As for my use case, I actually created a [rule for stylelint](https://github.com/stylelint/stylelint/pull/2474) that covers it, so there's not much left to worry about. 😄
