### ISSUE TITLE
Single quote being interpreted as element/pseudo-element.

### ISSUE THREAD

**Issue by gsoldateli** [keeganstreet/specificity#36]
Hello there!
First of all, great work. Is helping me a lot to practice specifity calculation.

The image below explains everything.

![Bug example](https://i.imgur.com/RaCGTWB.jpg)

Cheers!

**Comment by keeganstreet** [comment]
Hi @gsoldateli, thanks! I'm glad its helping.

When you use the negation pseudo-class in CSS, you don't need to use quotes. In fact, this is not valid CSS.

The specificity calculator does not currently validate CSS selectors. It will only give you an accurate specificity if the CSS selector is valid.
