### ISSUE TITLE
Comparison of specificities incomplete

### ISSUE THREAD

**Issue by davidlinner** [keeganstreet/specificity#37]
Calling `compare('#x .a .b', '#x #y')` results in -1, which means the first selector seems to be less specific than the second, but isn't. At least browsers tend to interpret specificity differently. When using the following simple example, the style rule with the first selector takes precedence.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>
        #x .a .b { color: green;  }
        #x #y { color: red;  }
    </style>
</head>
<body>
    <main id="x">
        <section id="y" class="a">
            <article class="b">foo</article>
        </section>
    </main>
</body>
</html>
```

The algorithm in the `compare` function implements the tie-breaking only. The first step should be to compare the sums of vector components.

**Comment by keeganstreet** [comment]
Hi David, there is no defect here. Thanks for providing the example code as it allows me to explain what's going on.

Selector 1 `#x .a .b` is targeting the `<article>` element, which contains the text `foo`. Selector 2 `#x #y` is targeting the `<section>` element, which is the parent of the `<article>`. Styles applied directly to an element will take precedence over any styles *inherited* from ancestor elements.

The CSS concept you might want to look up on more is [inheritance](https://developer.mozilla.org/en-US/docs/Learn/CSS/Introduction_to_CSS/Cascade_and_inheritance).

**Comment by davidlinner** [comment]
Hi Keegan, yes, sorry for the false alert. Seems I lost the overview when playing around with the example. Great library by the way.
