### ISSUE TITLE
Display specificity for groups of selectors

### ISSUE THREAD

**Issue by twpol** [keeganstreet/specificity#4]
When grouping selectors with a comma (http://www.w3.org/TR/css3-selectors/#grouping), the website (http://specificity.keegan.st/) simply displays the results for the first selector in the list. It would be nice to visualise all of the selectors in the list.

I would suggest two possible methods:
- Display the 4-coloured-boxes once for each selector in the input.
- Add a button to split the input (similar to duplicate) which creates a separate entry for each selector.

**Comment by keeganstreet** [comment]
I'll close this one off as commas can be used within a single selector nowadays, i.e. `:is(em, #foo)`
