### ISSUE TITLE
asterisk is not being taken into account

### ISSUE THREAD

**Issue by adrian-beachbody** [keeganstreet/specificity#42]
<img width="946" alt="Screen Shot 2020-04-13 at 2 28 43 PM" src="https://user-images.githubusercontent.com/60362332/79163044-21dcbb80-7d93-11ea-9792-ca0faafd4bc7.png">

While the specificity in the image is saying they are tied, chrome is saying that the top selector is more specific.

**Comment by keeganstreet** [comment]
Hi Adrian, I think what you're seeing here is that when two rules have
equal specificity, whichever rule comes last in the stylesheet will take
precedence. Try swapping the order of these rules in your CSS and see
what happens.

**Comment by adrian-beachbody** [comment]
You are correct. Sorry! Closing
