### ISSUE TITLE
Change the specificity to "a, b, c" three-segment representation

### ISSUE THREAD

**Issue by yisibl** [keeganstreet/specificity#46]
> specificityArray: the result as an array of numbers e.g. [0, 1, 0, 0]

[Selectors Level 3](https://www.w3.org/TR/2018/REC-selectors-3-20181106/#specificity) only has `a,b,c`

Safari's developer tools also only show `a,b,c`.

![image](https://user-images.githubusercontent.com/2784308/117607704-27235a00-b18f-11eb-8803-6c6040f7e823.png)

and 'css-specificity-calculator' site:
https://polypane.app/css-specificity-calculator/#selector=.foo%3Ahover%20%3E%20h1

**Comment by Kilian** [comment]
@yisibl Polypane actually uses specificity! The first 0 is there to represent inline styles, which trump all. Since they are not applicable when dealing with CSS selectors directly, we hide them for clarity.
