### ISSUE TITLE
Become as dependency of Bower

### ISSUE THREAD

**Issue by Miqueliu** [keeganstreet/specificity#47]
I need use this library for a custom one in JavaScript and it seems to be only prepared for NPM. Can you setup the source code for JS (removing the final `export` declaration and packaging up in a namespace) and register it in Bower?

**Comment by stefanullinger** [comment]
Hi @Miqueliu, I think using bower you can install this package directly from GitHub ([https://stackoverflow.com/questions/19348076/installing-a-dependency-with-bower-from-url-and-specify-version/19349338#19349338](https://stackoverflow.com/questions/19348076/installing-a-dependency-with-bower-from-url-and-specify-version/19349338#19349338)) as it contains a package.json file.

And looking at the docs, you should be able to use the UMD artifact to use this library in the browser: [https://github.com/keeganstreet/specificity#browser-usage-as-a-global-variable](https://github.com/keeganstreet/specificity#browser-usage-as-a-global-variable). Have you tried that already?

**Comment by Miqueliu** [comment]
It does not work. In the folder "bower_components", there is no files loaded.

**Comment by stefanullinger** [comment]
Hi @Miqueliu, you are right. I guess the dist files are only exported to NPM. Have you tried something like [bower-npm-resolve](https://github.com/mjeanroy/bower-npm-resolver)?!

**Comment by Miqueliu** [comment]
I followed the [indicated steps](https://github.com/mjeanroy/bower-npm-resolver#configuration-and-usage) and also I had to fix Bower's `overrides` (in `bower.json`) to get success.

Anyway, I think this is not the right method to load dependencies. It is very tricky and a maddening mess for the user that will want use my library.

**Comment by stefanullinger** [comment]
I get your point and once was also using bower a lot. But since the bower website itself mentions not to use it anymore, I am not sure that libraries like this will add a way to install via bower.

**Comment by Miqueliu** [comment]
Bower is deprecated, but not obsolete. It does not support own registering anymore, but the basic functionality (file `bower.json` with version tag) still works correctly.

I understand what you said, and I tried to migrate to another package manager, but I did not reached. :(

**Comment by Miqueliu** [comment]
Finally I got this with:

`jQuery.getScript( 'https://cdn.jsdelivr.net/npm/specificity@0.4.1/dist/specificity.min.js' );`

I don't like it but I have no choice.

**Comment by Miqueliu** [comment]
I got it by Bower! Installing with URL:

```sh
bower install --save https://cdn.jsdelivr.net/npm/specificity@0.4.1/dist/specificity.js
```
