### ISSUE TITLE
Add support for new pseudo-classes

### ISSUE THREAD

**Issue by emmanuelclement** [keeganstreet/specificity#51]
Hello, it would be great if one could add support for recent pseudo-classes:

https://developer.mozilla.org/en-US/docs/Web/CSS/:where
https://developer.mozilla.org/en-US/docs/Web/CSS/:is
https://developer.mozilla.org/en-US/docs/Web/CSS/:not

And some others listed on:
https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes

Edit: actually I don't know whether these selectors are taken into account or not.

**Comment by bartveneman** [comment]
Hey, support for this (and much more!) was added last week (❗) in [v1.0.0](https://github.com/keeganstreet/specificity/releases/tag/v1.0.0), see these tests for example: https://github.com/keeganstreet/specificity/blob/master/src/calculate.test.ts#L230-L246

**Comment by keeganstreet** [comment]
Yep, that's right 😄 These are working now and https://specificity.keegan.st/ has been updated too

**Comment by emmanuelclement** [comment]
Hello, nice! Thanx for your answers :-)
